
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Exception Handling Header for MicroBlaze Processor
*
*******************************************************************/



#define MICROBLAZE_EXCEPTIONS_ENABLED 1
